In [6]:
import numpy as np

Q1. Consider the following sensor readings: temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) A sensor has an average measurement error of +2°C. Perform the following without using a for loop: a. Add 2°C to every reading using vectorization. b. Convert all temperatures from Celsius to Fahrenheit using: F =9 5 C +32 c. Identify all readings greater than 32°C using Boolean indexing. d. Count how many readings exceed 32°C. e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.

In [7]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
temperature_without_error = temperature + 2
print(temperature_without_error)
temperature_in_fahrenheit = (temperature_without_error * 9/5) + 32
print(temperature_in_fahrenheit)
print(temperature > 32)
print(np.sum(temperature > 32))

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[False False False  True  True False  True  True]
4


Q2. The following matrix represents the number of daily steps recorded by four users over three days: steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]]) Perform the following: a. Calculate the total steps recorded. b. Calculate the mean number of steps. c. Find the maximum and minimum values. d. Calculate the total steps for each day using axis=0. e. Calculate the total steps for each user using axis=1. f. Find the user/day position containing the maximum number of steps using argmax().

In [8]:
steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]])
print("Total steps recorded:", steps.sum())
print("Mean number of steps:", steps.mean())
print("Maximum value:", steps.max())
print("Minimum value:", steps.min())
print("Total steps for each day:", steps.sum(axis=0))
print("Total steps for each user:", steps.sum(axis=1))
print("Maximum number of steps by a user are:", steps.argmax())
print("Maximum number of steps by a user are:", steps.argmax(axis=1))

Total steps recorded: 84200
Mean number of steps: 7016.666666666667
Maximum value: 9500
Minimum value: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Maximum number of steps by a user are: 11
Maximum number of steps by a user are: [2 2 1 2]


Q3. Write a Python program using NumPy to perform the following operations: a. Create the following NumPy array: original = np.array([1, 2, 3, 4, 5, 6]) b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset. c. Modify the first element of subset to 999 and display both original and subset. d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array. e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix. f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing: • First row  • Last row  • Second column  • Elements from rows 1–2 and columns 2–3  g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel(). h. Modify an element in the array returned by ravel() and observe whether the original array is affected. i. Modify an element in the array returned by flatten() and observe whether the original array is affected. j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.

In [9]:
original = np.array([1, 2, 3, 4, 5, 6])
subset = original[1:5]
print(subset)
subset[0]=999
print(subset)
copied_array=original.copy()
copied_array[0]=500
print(original)
print(copied_array)

[2 3 4 5]
[999   3   4   5]
[  1 999   3   4   5   6]
[500 999   3   4   5   6]


In [10]:
array = np.array(np.arange(1,13,1))
print(array)
reshaped_array=array.reshape(3,4)
print("Reshaped array:", reshaped_array)
print("First row: ", reshaped_array[1])
print("Last row: ", reshaped_array[2])
print("Second column: ", reshaped_array[:,1])
print("Elements from rows 1–2 and columns 2–3: ", reshaped_array[0:2,1:3])

flatten_reshaped_array = reshaped_array.flatten()
print("Flatten array:", flatten_reshaped_array)
ravel_reshaped_array = reshaped_array.ravel()
print("Ravel array:", ravel_reshaped_array)

ravel_reshaped_array[0] = 99
print("Ravel array:", ravel_reshaped_array)
print("Original array (ravel):", reshaped_array)
#yes the orginal array was changed

flatten_reshaped_array[0] = 500
print("Flatten array:", flatten_reshaped_array)
print("Original array (flatten):", reshaped_array)
#no the original array was not changed

print("Shape:", reshaped_array.shape)
print("ndim:", reshaped_array.ndim)
print("size:", reshaped_array.size)
print("dtype:", reshaped_array.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row:  [5 6 7 8]
Last row:  [ 9 10 11 12]
Second column:  [ 2  6 10]
Elements from rows 1–2 and columns 2–3:  [[2 3]
 [6 7]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel array: [99  2  3  4  5  6  7  8  9 10 11 12]
Original array (ravel): [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flatten array: [500   2   3   4   5   6   7   8   9  10  11  12]
Original array (flatten): [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
ndim: 2
size: 12
dtype: int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors: • Sleep hours  • Activity level  • Stress level  Consider: y = np.array([40, 65, 30, 85]) X = np.array([ [6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8] ]) Here, each row represents one user and each column represents a feature. Perform the following: a. Display the shape and dimensions of X. b. Calculate: X.T and explain what the transpose represents. c. Calculate the matrix product: X.T @ X d. Calculate the matrix inverse using: np.linalg.inv() where appropriate. e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋𝑋) 𝑋𝑦 using NumPy. f. Explain what the resulting coefficients represent in the context of the three user features. g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.

In [11]:
y = np.array([40, 65, 30, 85])
X = np.array([[6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8]])
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)
print("Transpose of X:", X.T)
matrix_inverse = np.linalg.inv(X.T @ X)
print("Matrix inverse of X:", matrix_inverse)
coefficients = matrix_inverse @ X.T @ y
print("Coefficients:", coefficients)

Shape of X: (4, 3)
Dimensions of X: 2
Transpose of X: [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
Matrix inverse of X: [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients: [-0.15921454  0.14083853 10.06302242]


### e. Explanation of Vectorization and Boolean Indexing Efficiency

**Vectorization** is a technique in NumPy (and other numerical libraries) that allows operations to be performed on entire arrays at once, rather than on individual elements using explicit loops. This is significantly more efficient for several reasons:

1.  **Optimized C/Fortran Code:** NumPy operations are implemented in highly optimized, pre-compiled C or Fortran code. This native code executes much faster than Python loops, which involve interpreter overhead for each iteration.
2.  **Reduced Overhead:** Python loops involve significant overhead due to type checking, object creation, and function calls for each element. Vectorized operations reduce this overhead by performing the operation in a single call to an optimized function.
3.  **Parallel Processing:** Modern CPUs are designed for parallel processing, and vectorized operations can leverage these capabilities by operating on multiple data elements simultaneously.

**Boolean Indexing** allows you to select subsets of data from an array based on a boolean condition, also in a vectorized manner. Instead of iterating through each element and checking a condition individually, a boolean array (of the same shape as the original array) is created where `True` indicates elements that meet the condition and `False` indicates those that don't. This boolean array is then used to directly select the desired elements. The efficiency benefits are similar to general vectorization:

*   It avoids explicit Python loops for conditional checks and element selection.
*   It relies on optimized underlying implementations.

Together, vectorization and Boolean indexing drastically improve the speed and readability of numerical computations in Python compared to traditional looping constructs, especially for large datasets.

### f. Explanation of Coefficients

The coefficients ($\beta$) represent the estimated impact of each feature (sleep hours, activity level, stress level) on the assistance score. Assuming a linear model, each coefficient indicates how much the assistance score is expected to change for a one-unit increase in the corresponding feature, while holding other features constant.

*   A positive coefficient suggests that an increase in that feature leads to an increase in the assistance score.
*   A negative coefficient suggests that an increase in that feature leads to a decrease in the assistance score.

The magnitude of the coefficient indicates the strength of this relationship.

In [12]:
new_user = np.array([5, 40, 7])
predicted_score = np.dot(new_user, coefficients)
print(f"Predicted assistance score for the new user: {predicted_score:.2f}")

Predicted assistance score for the new user: 75.28
