In [ ]:
import numpy as np

In [ ]:
#Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
#a) Addition of 2 in all the element
#b) Multiply 3 with all the elements
#c) Divide every element by 2

In [ ]:
np_array = np.array([1,2,3,4,5])
print("Adding 2:", np_array+2)
print("Multiplying 3:", np_array*3)
print("Dividing by 2:", np_array/2)

Adding 2: [3 4 5 6 7]
Multiplying 3: [ 3  6  9 12 15]
Dividing by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
#Q.2 Questions on Basic NumPy Array:
#a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
#b) Find the most frequent value and their indice(s) in the following arrays:
#i. x = np.array([1,2,3,4,5,1,2,1,1,1])
#ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [ ]:
np_array = np.array([1, 2, 3, 6, 4, 5])
print("Reversed array:", np_array[::-1])
x=np.array([1,2,3,4,5,1,2,1,1,1])
print("The most frequently occurring element in x is", np.bincount(x).argmax())
print("The indices of the most frequently occurring element in x are", np.where(x==np.bincount(x).argmax()))
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("The most frequently occurring element in y is", np.bincount(y).argmax())
print("The indices of the most frequently occurring element in y are", np.where(y==np.bincount(y).argmax()))

Reversed array: [5 4 6 3 2 1]
The most frequently occurring element in x is 1
The indices of the most frequently occurring element in x are (array([0, 5, 7, 8, 9]),)
The most frequently occurring element in y is 1
The indices of the most frequently occurring element in y are (array([0, 1, 2]),)


In [ ]:
#Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
#a) Access 1st row, 2nd column
#b) Access 3rd row, 1st column

In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row, 2nd column:", arr[0,1])
print("3rd row, 1st column:", arr[2,0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [ ]:
#Q.4 Write program to create an 1-D NumPy array named <<Your Name>>
#with evenly spaced 25 numbers from 10 to 100 using linspace().
#Print the dimensions of the array, shape, total elements, the data type
#of each element and total number of bytes consumed by the array.
#Find the transpose of this array using reshape() attribute.
#Can we do the same with T attribute?

In [ ]:
aradhya = np.linspace(10,100,25)
print("Array:", aradhya.ndim)
print("Shape:", aradhya.shape)
print("Total elements:", aradhya.size)
print("Data type of each element:", aradhya.dtype)
print("Total number of bytes consumed by the array:", aradhya.nbytes)

Array: 1
Shape: (25,)
Total elements: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200


In [ ]:
#Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
#with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.
#Compute the mean, median, max, min, unique elements.
#Reshape the array to four rows and three columns and name it as
#reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
#columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
ucs420_aradhya = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
print("Mean: ", np.mean(ucs420_aradhya))
print("Median: ", np.median(ucs420_aradhya))
print("Max: ", np.max(ucs420_aradhya))
print("Min: ", np.min(ucs420_aradhya))
print("Unique elements: ", np.unique(ucs420_aradhya))

reshaped_ucs420_aradhya = ucs420_aradhya.reshape(4,3)
print("Reshaped array: ", reshaped_ucs420_aradhya)

resized_ucs420_aradhya = np.resize(ucs420_aradhya, (2,3))
print("Resized array: ", resized_ucs420_aradhya)

Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:  [[10 20 30]
 [40 50 60]]
